
name: Secure DevOps Pipeline
on:
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 0 * * 0' # Wekelijkse scan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Tests
      run: |
        python -m unittest discover

  security_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: SAST Scan (Bandit)
      run: |
        pip install bandit
        bandit -r .

    - name: Install Safety
      uses: pyupio/safety-action@v1
      with: 
        api-key: ${{ secrets.SAFETY_ACTION }}
